galaxy_info:
  author: Nikita Kononov
  description: Ansible role for deploying OpenShift operators using OLM from different catalog sources.
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  galaxy_tags:
    - openshift
    - kubernetes
    - operator
    - olm
    - deployment
dependencies: []
